name: Run FastAPI Tests

on:
  push:
    branches:
      - main  # Run tests when pushing to main branch
  pull_request:
    branches:
      - main  # Run tests for pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your project has this file
          pip install pytest mongomock fastapi uvicorn  # Ensure required test dependencies

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -v
