name: Run FastAPI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug:List all files in backend directory
        run: ls -R backend/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mongomock fastapi uvicorn pymongo

      - name: Verify `pytest` installation
        run: pytest --version  
        
      - name: Run tests with pytest (Explicitly Specify `backend/`)
        run: pytest backend/ --maxfail=1 --disable-warnings -v
