name: Run FastAPI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "True"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mongomock fastapi uvicorn pymongo httpx python-dotenv python-jose fastapi_keycloak_middleware

      - name: Verify pytest installation
        run: pytest --version

      - name: Run pytest
        run: |
          pytest backend/